name: Generate Binance Vision URLs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Everyday at 03:00 UTC

jobs:
  gen:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.8"
      - name: install deps
        run: pip install aiohttp aiofiles
      - name: generate urls
        run: bash gen_url.sh
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "chore: update binance vision urls"
